version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "4501:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=Shota_Elearning_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql:rw
    command: --innodb_use_native_aio=0
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/Shota_Elearning
    ports:
      - "3501:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
